### ISSUE TITLE
How to Write Kafka Classes?

### ISSUE THREAD

**Issue by realmarkcross** [rapideinternet/laravel-queue-kafka#10]
I have a working Kafka server and Laravel client with your package installed and I understand how the Laravel Queue system works but could you provide some working examples for producing Topics, Consumers and Producers as well as any administrative functions, please?

**Comment by vagh** [comment]
Yes! we need some example to learn how to use. If you have free time.

**Comment by petermein** [comment]
I will plan in to make a demo, upcoming monday

**Comment by petericebear** [comment]
Any update on this? Curious how to integrate kafka in to Laravel.

**Comment by petermein** [comment]
I've added some links to interesting reading material. These explain when an why you coud use a kafka queue. I've also added some ways to create 2 diffrent consumer groups for diffrent tasks.

I haven't been able to make any examples of applications that explicitly need kafka. But an example could be when implementing CQRS into your application.
