### ISSUE TITLE
undefined method

### ISSUE THREAD

**Issue by xxming** [rapideinternet/laravel-queue-kafka#11]
I'm getting this error when i try to use your library. I have installed  RDKafka C library and the PECL package.
The error:
local.ERROR: Call to undefined method RdKafka\Message::get() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method RdKafka\\Message::get() at /home/vagrant/Code/Laravel/vendor/rapide/laravel-queue-kafka/src/Queue/Jobs/KafkaJob.php:137)

**Comment by chris-rs** [comment]
I also got the error you mentioned. I inspected the code: KafkaJob method getJobId() does an erroneous call to $this->message->get('correlation_id'); but Message from RdKafka does not have a get method.
I think it should be:
```
public function getJobId()
{
     return $this->message->key;
}
```
Fixing this, solves the problem. I will open a pull request to fix this.

**Comment by petermein** [comment]
Il fix this in the next release, thanks @chris-rs
