### ISSUE TITLE
php artisan queue:work on multiple queue

### ISSUE THREAD

**Issue by L3o-pold** [rapideinternet/laravel-queue-kafka#18]
I got multiple topics and it only process one queue.

For example:

`php artisan queue:work --daemon --tries=1 --delay=5 --queue=default,low kafka`
Will NOT process any job

`php artisan queue:work --daemon --tries=1 --delay=5 kafka`
Will process only the job from the `KAFKA_QUEUE` env queue

When debugging I saw that the `pop` function from `KafkaQueue.php` will be call for every queue but the `RD_KAFKA_RESP_ERR__TIMED_OUT` error will be returned every time.

Is there something I am missing?

**Comment by petermein** [comment]
Thank you for the pull request!
