### ISSUE TITLE
When support Laravel 5.*

### ISSUE THREAD

**Issue by vagh** [rapideinternet/laravel-queue-kafka#8]
Hey, Nice project! I want use it in Laravel 5.5, But have some trouble when i ues `composer require rapide/laravel-queue-kafka`:

![image](https://user-images.githubusercontent.com/6220019/37275312-c9753918-2619-11e8-84f1-07ec42efa7ae.png)

Hope you can update this verison.

**Comment by petermein** [comment]
Il have a look at it

**Comment by petermein** [comment]
I've released a new version support 5.5 and 5.6! Good luck @vagh

**Comment by vagh** [comment]
Thank you!! You've got me a big hurry！！
