### ISSUE TITLE
Class 'RdKafka\Producer' not found

### ISSUE THREAD

**Issue by arielconti10** [rapideinternet/laravel-queue-kafka#9]
I'm getting this error when i try to use your library. 
The error is going on registerDependecies() method in the LaravelQueueKafkaServiceProvider.php line 47

**Comment by petermein** [comment]
The library must be missing, did you install the RDKafka C library and the PECL package?

**Comment by arielconti10** [comment]
Yes, the library is installed so is the PECL package. I'm trying to use with laravel, i think it is something about namespaces.

**Comment by xiaoerli520** [comment]
same question.

**Comment by petermein** [comment]
I've added some comment for checking if the extension is actually loaded. Please try these comment, including the new depency in the composer.json
